# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: base.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbase.proto\x12\x04\x62\x61se\"\x07\n\x05\x45mpty\"\x14\n\x04ISIN\x12\x0c\n\x04isin\x18\x01 \x01(\t\"\x1b\n\nStockPrice\x12\r\n\x05price\x18\x01 \x01(\x01\"4\n\x05\x41sset\x12\x0c\n\x04isin\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x05\x12\r\n\x05price\x18\x03 \x01(\x01\"a\n\x05Order\x12\r\n\x05token\x18\x01 \x01(\t\x12\x1a\n\x05\x61sset\x18\x02 \x01(\x0b\x32\x0b.base.Asset\x12\x1d\n\x04type\x18\x03 \x01(\x0e\x32\x0f.base.OrderType\x12\x0e\n\x06is_buy\x18\x04 \x01(\x08\"5\n\x12\x43\x61ncelOrderRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x10\n\x08order_id\x18\x02 \x01(\x04*3\n\tOrderType\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\n\n\x06MARKET\x10\x01\x12\t\n\x05LIMIT\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'base_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ORDERTYPE._serialized_start=288
  _ORDERTYPE._serialized_end=339
  _EMPTY._serialized_start=20
  _EMPTY._serialized_end=27
  _ISIN._serialized_start=29
  _ISIN._serialized_end=49
  _STOCKPRICE._serialized_start=51
  _STOCKPRICE._serialized_end=78
  _ASSET._serialized_start=80
  _ASSET._serialized_end=132
  _ORDER._serialized_start=134
  _ORDER._serialized_end=231
  _CANCELORDERREQUEST._serialized_start=233
  _CANCELORDERREQUEST._serialized_end=286
# @@protoc_insertion_point(module_scope)
