# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dispatcher.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import base_pb2 as base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x64ispatcher.proto\x12\ndispatcher\x1a\nbase.proto\"\x89\x01\n\x0bOrderStatus\x12\r\n\x05token\x18\x01 \x01(\t\x12\x1a\n\x05\x61sset\x18\x02 \x01(\x0b\x32\x0b.base.Asset\x12\x0e\n\x06is_buy\x18\x03 \x01(\x08\x12\x10\n\x08order_id\x18\x04 \x01(\x03\x12-\n\x0ctransactions\x18\x05 \x03(\x0b\x32\x17.dispatcher.Transaction\",\n\x0bTransaction\x12\r\n\x05price\x18\x01 \x01(\x01\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x05\x32L\n\x0fGatewayReceiver\x12\x39\n\x0fSendOrderStatus\x12\x17.dispatcher.OrderStatus\x1a\x0b.base.Empty\"\x00\x32\xdb\x01\n\x11\x44ispatcherGateway\x12\x31\n\x0fGetCurrentPrice\x12\n.base.ISIN\x1a\x10.base.StockPrice\"\x00\x12\x31\n\x0fGetOpeningPrice\x12\n.base.ISIN\x1a\x10.base.StockPrice\"\x00\x12(\n\nPlaceOrder\x12\x0b.base.Order\x1a\x0b.base.Empty\"\x00\x12\x36\n\x0b\x43\x61ncelOrder\x12\x18.base.CancelOrderRequest\x1a\x0b.base.Empty\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dispatcher_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ORDERSTATUS._serialized_start=45
  _ORDERSTATUS._serialized_end=182
  _TRANSACTION._serialized_start=184
  _TRANSACTION._serialized_end=228
  _GATEWAYRECEIVER._serialized_start=230
  _GATEWAYRECEIVER._serialized_end=306
  _DISPATCHERGATEWAY._serialized_start=309
  _DISPATCHERGATEWAY._serialized_end=528
# @@protoc_insertion_point(module_scope)
