# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import dispatcher_pb2 as dispatcher__pb2


class GatewayReceiverStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendOrderStatus = channel.unary_unary(
                '/GatewayReceiver/SendOrderStatus',
                request_serializer=dispatcher__pb2.OrderStatus.SerializeToString,
                response_deserializer=dispatcher__pb2.Empty.FromString,
                )


class GatewayReceiverServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendOrderStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GatewayReceiverServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendOrderStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.SendOrderStatus,
                    request_deserializer=dispatcher__pb2.OrderStatus.FromString,
                    response_serializer=dispatcher__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GatewayReceiver', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GatewayReceiver(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendOrderStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GatewayReceiver/SendOrderStatus',
            dispatcher__pb2.OrderStatus.SerializeToString,
            dispatcher__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class DispatcherGatewayStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCurrentPrice = channel.unary_unary(
                '/DispatcherGateway/GetCurrentPrice',
                request_serializer=dispatcher__pb2.ISIN.SerializeToString,
                response_deserializer=dispatcher__pb2.StockPrice.FromString,
                )
        self.GetOpeningPrice = channel.unary_unary(
                '/DispatcherGateway/GetOpeningPrice',
                request_serializer=dispatcher__pb2.ISIN.SerializeToString,
                response_deserializer=dispatcher__pb2.StockPrice.FromString,
                )
        self.PlaceOrder = channel.unary_unary(
                '/DispatcherGateway/PlaceOrder',
                request_serializer=dispatcher__pb2.Order.SerializeToString,
                response_deserializer=dispatcher__pb2.Empty.FromString,
                )
        self.CancelOrder = channel.unary_unary(
                '/DispatcherGateway/CancelOrder',
                request_serializer=dispatcher__pb2.CancelOrderRequest.SerializeToString,
                response_deserializer=dispatcher__pb2.Empty.FromString,
                )


class DispatcherGatewayServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCurrentPrice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOpeningPrice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlaceOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DispatcherGatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCurrentPrice': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCurrentPrice,
                    request_deserializer=dispatcher__pb2.ISIN.FromString,
                    response_serializer=dispatcher__pb2.StockPrice.SerializeToString,
            ),
            'GetOpeningPrice': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOpeningPrice,
                    request_deserializer=dispatcher__pb2.ISIN.FromString,
                    response_serializer=dispatcher__pb2.StockPrice.SerializeToString,
            ),
            'PlaceOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaceOrder,
                    request_deserializer=dispatcher__pb2.Order.FromString,
                    response_serializer=dispatcher__pb2.Empty.SerializeToString,
            ),
            'CancelOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelOrder,
                    request_deserializer=dispatcher__pb2.CancelOrderRequest.FromString,
                    response_serializer=dispatcher__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DispatcherGateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DispatcherGateway(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCurrentPrice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DispatcherGateway/GetCurrentPrice',
            dispatcher__pb2.ISIN.SerializeToString,
            dispatcher__pb2.StockPrice.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetOpeningPrice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DispatcherGateway/GetOpeningPrice',
            dispatcher__pb2.ISIN.SerializeToString,
            dispatcher__pb2.StockPrice.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PlaceOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DispatcherGateway/PlaceOrder',
            dispatcher__pb2.Order.SerializeToString,
            dispatcher__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CancelOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DispatcherGateway/CancelOrder',
            dispatcher__pb2.CancelOrderRequest.SerializeToString,
            dispatcher__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
