# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import FE_pb2 as FE__pb2


class FEServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStocksList = channel.unary_unary(
                '/FEService/GetStocksList',
                request_serializer=FE__pb2.Empty.SerializeToString,
                response_deserializer=FE__pb2.StocksList.FromString,
                )
        self.GetCurrentPrice = channel.unary_unary(
                '/FEService/GetCurrentPrice',
                request_serializer=FE__pb2.ISIN.SerializeToString,
                response_deserializer=FE__pb2.StockPrice.FromString,
                )
        self.GetOpeningPrice = channel.unary_unary(
                '/FEService/GetOpeningPrice',
                request_serializer=FE__pb2.ISIN.SerializeToString,
                response_deserializer=FE__pb2.StockPrice.FromString,
                )
        self.GetPortfolio = channel.unary_unary(
                '/FEService/GetPortfolio',
                request_serializer=FE__pb2.Token.SerializeToString,
                response_deserializer=FE__pb2.Portfolio.FromString,
                )
        self.PlaceOrder = channel.unary_unary(
                '/FEService/PlaceOrder',
                request_serializer=FE__pb2.Order.SerializeToString,
                response_deserializer=FE__pb2.Empty.FromString,
                )
        self.CancelOrder = channel.unary_unary(
                '/FEService/CancelOrder',
                request_serializer=FE__pb2.CancelOrderRequest.SerializeToString,
                response_deserializer=FE__pb2.Empty.FromString,
                )


class FEServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetStocksList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCurrentPrice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOpeningPrice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPortfolio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlaceOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FEServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStocksList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStocksList,
                    request_deserializer=FE__pb2.Empty.FromString,
                    response_serializer=FE__pb2.StocksList.SerializeToString,
            ),
            'GetCurrentPrice': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCurrentPrice,
                    request_deserializer=FE__pb2.ISIN.FromString,
                    response_serializer=FE__pb2.StockPrice.SerializeToString,
            ),
            'GetOpeningPrice': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOpeningPrice,
                    request_deserializer=FE__pb2.ISIN.FromString,
                    response_serializer=FE__pb2.StockPrice.SerializeToString,
            ),
            'GetPortfolio': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPortfolio,
                    request_deserializer=FE__pb2.Token.FromString,
                    response_serializer=FE__pb2.Portfolio.SerializeToString,
            ),
            'PlaceOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaceOrder,
                    request_deserializer=FE__pb2.Order.FromString,
                    response_serializer=FE__pb2.Empty.SerializeToString,
            ),
            'CancelOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelOrder,
                    request_deserializer=FE__pb2.CancelOrderRequest.FromString,
                    response_serializer=FE__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FEService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FEService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetStocksList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FEService/GetStocksList',
            FE__pb2.Empty.SerializeToString,
            FE__pb2.StocksList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCurrentPrice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FEService/GetCurrentPrice',
            FE__pb2.ISIN.SerializeToString,
            FE__pb2.StockPrice.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetOpeningPrice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FEService/GetOpeningPrice',
            FE__pb2.ISIN.SerializeToString,
            FE__pb2.StockPrice.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPortfolio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FEService/GetPortfolio',
            FE__pb2.Token.SerializeToString,
            FE__pb2.Portfolio.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PlaceOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FEService/PlaceOrder',
            FE__pb2.Order.SerializeToString,
            FE__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CancelOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FEService/CancelOrder',
            FE__pb2.CancelOrderRequest.SerializeToString,
            FE__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
