# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: front.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import base_pb2 as base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x66ront.proto\x12\x05\x66ront\x1a\nbase.proto\"*\n\nStocksList\x12\x1c\n\x06stocks\x18\x01 \x03(\x0b\x32\x0c.front.Stock\"G\n\x05Stock\x12\x0c\n\x04isin\x18\x01 \x01(\t\x12\x0e\n\x06ticker\x18\x02 \x01(\t\x12\x11\n\tfull_name\x18\x03 \x01(\t\x12\r\n\x05\x61\x62out\x18\x04 \x01(\t\"\x16\n\x05Token\x12\r\n\x05token\x18\x01 \x01(\t\"(\n\tPortfolio\x12\x1b\n\x06\x61ssets\x18\x01 \x03(\x0b\x32\x0b.base.Asset2\xbb\x02\n\x0c\x46rontService\x12\x31\n\rGetStocksList\x12\x0b.base.Empty\x1a\x11.front.StocksList\"\x00\x12\x31\n\x0fGetCurrentPrice\x12\n.base.ISIN\x1a\x10.base.StockPrice\"\x00\x12\x31\n\x0fGetOpeningPrice\x12\n.base.ISIN\x1a\x10.base.StockPrice\"\x00\x12\x30\n\x0cGetPortfolio\x12\x0c.front.Token\x1a\x10.front.Portfolio\"\x00\x12(\n\nPlaceOrder\x12\x0b.base.Order\x1a\x0b.base.Empty\"\x00\x12\x36\n\x0b\x43\x61ncelOrder\x12\x18.base.CancelOrderRequest\x1a\x0b.base.Empty\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'front_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STOCKSLIST._serialized_start=34
  _STOCKSLIST._serialized_end=76
  _STOCK._serialized_start=78
  _STOCK._serialized_end=149
  _TOKEN._serialized_start=151
  _TOKEN._serialized_end=173
  _PORTFOLIO._serialized_start=175
  _PORTFOLIO._serialized_end=215
  _FRONTSERVICE._serialized_start=218
  _FRONTSERVICE._serialized_end=533
# @@protoc_insertion_point(module_scope)
